---
aptget_update_cache_valid_time: 1800
aptget_distupgrade: true

aptget_install:
  - mc
  - nano
  - sysv-rc-conf
  - python-pip
  - python-dev
  - libmysqlclient-dev
  - python-jmespath
  - unzip
  - git
  - composer
#  - ngrok-client

php_max_input_vars: 1000
php_memory_limit: 512M
php_display_errors: Off
php_post_max_size: 48M
php_upload_max_filesize: 12M
php_max_file_uploads: 20
php_date_timezone: Europe/Madrid

mariadb_databases:
  - prestashop

mariadb_users:
  user1:
    name: "prestashop"
    password: "prestashop"
    priv: "prestashop.*:ALL"


mariadb_root_password: prestashop
mariadb_utiles_bd: true
mariadb_cron_backup: false


mariadb_options:
  bind_address: '127.0.0.1'
  performance_schema: on
  skip_name_resolve: 1
  max_connections: 100
  connect_timeout: 2
  max_allowed_packet: 10M
  innodb_buffer_pool_instances: 1
  innodb_buffer_pool_size: 50M
  innodb_log_file_size: 12M
  table_cache: 1000
  tmp_table_size: 50M
  max_heap_table_size: 25M
  query_cache_type: 1
  query_cache_limit: 2M
  query_cache_size: 10M
  query_cache_min_res_unit: 2k
  join_buffer_size: 512k
  sort_buffer_size: 512k
  read_buffer_size: 512k
  read_rnd_buffer_size: 1M
  key_buffer: 125M
  slow_query_log: true
  long_query_time: 3
  log_slow_admin_statements: true
  log_queries_not_using_indexes: true

nginx_vhosts_root: "/home/webs"

nginx_vhosts:
  prestashop:
    default_server: true # Sólo debe existir uno como default server
    activado: true
    archivo_conf: "prestashop.test.conf"
    dominio: "prestashop.test"
    sin_www:  true
    ssl: false
    cache_nginx: false
    cms: "prestashop"
    prestashop_admin: "adminvap72"
    root: "{{ nginx_vhosts_root }}/prestashop.test/public"
    index: "index.html index.htm index.php"

nginx_vhosts_activados:
  - prestashop.test.conf

prestashop_root_path: "{{ nginx_vhosts_root }}/prestashop.test/public"
prestashop_db_create: 1
prestashop_db_clear: 1
prestashop_db_server: "localhost"
prestashop_db_name: "prestashop"
prestashop_db_user: "prestashop"
prestashop_db_prefix: "vap_"
prestashop_db_password: "prestashop"
prestashop_language: "es"
prestashop_country: "es"
prestashop_timezone: "Europe/Madrid"

prestashop_firstname: "VAP"
prestashop_lastname: "Developer"
prestashop_password: "prestashop"
prestashop_email: "vap@prestashop.test"

prestashop_admin_folder_name: "adminvap72"
prestashop_check_file_name: "prestashop-vap-installed.txt"

phpmyadmin_folder: "{{ prestashop_root_path }}/phpmyadmin"